services:
  - type: web
    name: leakway-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node src/app.js"
    envVars:
      - key: NODE_VERSION
        value: 18.13.0
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: superadmin123
      - key: JWT_SECRET
        value: changemesecret
    autoDeploy: true
    region: frankfurt
    rootDir: backend
